Aluno/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Aluno'

urlpatterns = [
	path('Painel-Aluno', PainelAlunoView.as_view(), name='painelAlunoUrl'),
	path('Painel-Aluno/Perfil', PerfilView.as_view(), name='perfilUrl')
]

Corretor/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Corretor'

urlpatterns = [
	path('Painel-Corretor', PainelCorretorView.as_view(), name='painelCorretorUrl'),
]

Redacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Redacao'

urlpatterns = [
	path('Terminal-Aluno/Enviar-Redacao', EnviarRedacaoView.as_view(), name='enviarRedacaoUrl'),
	path('Painel-Corretor/pedir-redacao', PedirRedacaoView.as_view(), name='pedirRedacaoUrl'),
	path('Painel-Corretor/corrigir', CorrigirView.as_view(), name='corrigirUrl')
]

projeto_redacao/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('Visitante.urls')),
    url(r'^', include('Aluno.urls')),
    url(r'^', include('Redacao.urls')),
    url(r'^', include('Corretor.urls')),
    url(r'^', include('Pagamento.urls')),
    url(r'^retorno/pagseguro/', include('pagseguro.urls')),
]

Corretor/models.py
from django.db import models

# Create your models here.

Corretor/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate

from Redacao.models import (Proposta, Redacao)

class PainelCorretorView(View):
	def get(self, request):
		if request.user.is_authenticated:
			if request.user.has_perm('Usuarios.acesso_painel_corretor'):
				propostas = Proposta.objects.filter(em_uso = True)
				ele_tem_redacao = request.user.redacoes.filter(corrigida=False)
				if ele_tem_redacao:
					can_corrigir = ''
				else:
					can_corrigir = "disabled"
				if Redacao.objects.filter(corrigida=False) and not ele_tem_redacao:
					can_ask_redacao = ''
				else:
					can_ask_redacao = "disabled"

				dic = {'propostas': propostas, 'can_ask_redacao': can_ask_redacao, 'can_corrigir': can_corrigir}
				return render(request, 'Corretor/painelCorretor.html', dic)
			else:
				messages.add_message(request, messages.INFO, 'Você não tem permição de entrar no painel de corretores')
				return redirect('Visitante:infoFalhaUrl')
		else:
			messages.add_message(request, messages.INFO, 'Você não está logado')
			return redirect('Visitante:infoFalhaUrl')

Corretor/templates/Corretor/painelCorretor.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Painel de Corretor</title>
</head>
<body>
	<h1>Este é o painel do Corretor</h1>
	{% for message in messages %}
		<li>{{ message }}</li>
	{% endfor %}

	<h3>Essas são as propostas que podem ser escolhidas</h3>
	{% for p in propostas %}
		<img style="width: 200px; margin: 10px" src="{% static '' %}{{ p.imagem }}">
	{% endfor %}
	<h3>Suas Redações</h3>

	<br>
	<form action="{% url 'Redacao:pedirRedacaoUrl' %}" method="post">
		{% csrf_token %}
		<input type="submit" value="Pedir Redação" {{ can_ask_redacao }}/>
	</form>
	<br>
	<form action="{% url 'Redacao:corrigirUrl' %}" method="get">
		{% csrf_token %}
		<input type="submit" value="Corrigir" {{ can_corrigir }}/>
	</form>
</body>
</html>