Aluno/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Aluno'

urlpatterns = [
	path('Painel-Aluno', PainelAlunoView.as_view(), name='painelAlunoUrl'),
	path('Painel-Aluno/Perfil', PerfilView.as_view(), name='perfilUrl')
]

Pagamento/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Pagamento'

urlpatterns = [
	path('Terminal-Aluno/Compra', CompraView.as_view(), name='compraUrl'),
]

Redacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Redacao'

urlpatterns = [
	path('Terminal-Aluno/Enviar-Redacao', EnviarRedacaoView.as_view(), name='enviarRedacaoUrl'),
	path('Painel-Corretor/pedir-redacao', PedirRedacaoView.as_view(), name='pedirRedacaoUrl'),
	path('Painel-Corretor/corrigir', CorrigirView.as_view(), name='corrigirUrl')
]

projeto_redacao/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('Visitante.urls')),
    url(r'^', include('Aluno.urls')),
    url(r'^', include('Redacao.urls')),
    url(r'^', include('Corretor.urls')),
    url(r'^', include('Pagamento.urls')),
    url(r'^retorno/pagseguro/', include('pagseguro.urls')),
]

Aluno/models.py
from django.db import models

# Create your models here.

Aluno/forms.py
from django import forms

from django.utils import timezone

from Usuarios.models import User

class ModifyUserForm(forms.Form):
	email             = forms.EmailField(max_length=255, required=False)
	password1         = forms.CharField(label='Senha', widget=forms.PasswordInput, required=False, max_length=128)
	password2         = forms.CharField(label='Confirme a Senha', widget=forms.PasswordInput, required=False, max_length=128)
	primeiro_nome     = forms.CharField(required=False, max_length=20)
	segundo_nome      = forms.CharField(required=False, max_length=60)
	cep               = forms.CharField(required=False, max_length=9)

	def save(self, user, commit=True):
		if self['email'].data:
			user.email = self['email'].data
		if self['password1'].data:
			user.set_password(self.cleaned_data["password1"])
		if self['primeiro_nome'].data:
			user.primeiro_nome = self['primeiro_nome'].data
		if self['segundo_nome'].data:
			user.segundo_nome = self['segundo_nome'].data
		if self['cep'].data:
			user.cep = self['cep'].data

		if commit:
			user.save()
		return user

class CompraForm(forms.Form):
	quantidade        = forms.IntegerField()

Aluno/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate

from .forms import *
from Redacao.models import (Proposta, Redacao)

class PainelAlunoView(View):
	def get(self, request):
		if request.user.is_authenticated:
			if request.user.has_perm('Usuarios.acesso_painel_aluno'):
				propostas = Proposta.objects.filter(em_uso = True)
				redacoes  = request.user.redacoes.all()
				f = CompraForm()

				dic = {'propostas': propostas, 'redacoes': redacoes,'f': f}

				return render(request, 'Aluno/painelAluno.html', dic)
			else:
				messages.add_message(request, messages.INFO, 'Você não tem permição de entrar no painel de alunos')
				return redirect('Visitante:infoFalhaUrl')
		else:
			messages.add_message(request, messages.INFO, 'Você não está logado')
			return redirect('Visitante:infoFalhaUrl')

class PerfilView(View):
	def get(self, request):
		if request.user.is_authenticated:
			if request.user.has_perm('Usuarios.acesso_terminal_aluno'):
				f = ModifyUserForm()
				dic = { 'f': f }

				return render(request, 'Aluno/perfil.html', dic)
			else:
				messages.add_message(request, messages.INFO, 'Você não tem permição de entrar no terminal de alunos')
				return redirect('Visitante:infoFalhaUrl')
		else:
			messages.add_message(request, messages.INFO, 'Você não está logado')
			return redirect('Visitante:infoFalhaUrl')
	def post(self, request):
		if request.user.is_authenticated:
			if request.user.has_perm('Usuarios.acesso_terminal_aluno'):
				f = ModifyUserForm(request.POST)

				if f.is_valid():
					f.save(user=request.user)
					messages.success(request, 'Informações alteradas com sucesso!')
				else:
					messages.error(request, f.errors)
				return redirect('Aluno:perfilUrl')
			else:
				messages.add_message(request, messages.INFO, 'Você não tem permição de entrar no terminal de alunos')
				return redirect('Visitante:infoFalhaUrl')
		else:
			messages.add_message(request, messages.INFO, 'Você não está logado')
			return redirect('Visitante:infoFalhaUrl')

Aluno/templates/Aluno/painelAluno.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Painel de Aluno</title>
</head>
<body>
	<h1>Este é o painel do Aluno</h1>
	<h3>Escolha sua proposta agora!</h3>
	{% for p in propostas %}
		<img style="width: 200px; margin: 10px" src="{% static '' %}{{ p.imagem }}">
	{% endfor %}
	<h3>Suas Redações</h3>
	{% for r in redacoes %}
		<p>redação</p>
		<img style="width: 200px; margin: 10px" src="{{ redacao_url }}{{ r.redacao }}">
		{% if r.corrigida %}
			<p>correção</p>
			<img style="width: 200px; margin: 10px" src="{{ redacao_url }}{{ r.correcao }}">
			<p>competencia 1: {{r.nota_competencia_1}} | competencia 2: {{ r.nota_competencia_2 }} | competencia 3: {{ r.nota_competencia_3 }} | competencia 4: {{ r.nota_competencia_4 }} | competencia 5: {{ r.nota_competencia_5 }} | NOTA: {{r.nota}}</p>
		{% endif %}
	{% endfor %}
	<h4>Comprar correções</h4>
	<form method="POST" action="{% url 'Pagamento:compraUrl' %}">
		{% csrf_token %}
		{{ f.as_p }}
		<button class="" type="submit" name="action">
			comprar
		</button>
	</form>
	<p><a href="{% url 'Aluno:perfilUrl' %}">Alterar informações de Perfil</a></p>
	<p><a href="{% url 'Redacao:enviarRedacaoUrl' %}">Enviar Redação</a></p>
</body>
</html>

Aluno/templates/Aluno/perfil.html
<!DOCTYPE html>
<html>
<head>
	<title>Perfil</title>
</head>
<body>
	<h3>Alterar informações do Perfil</h3>
	{% if messages %}
	<ul>
		{% for message in messages %}
			<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<form method="POST">
		{% csrf_token %}
		<p><label for="id_email">Email:</label> <input name="email" maxlength="255" id="id_email" type="email"></p>
		<p><label for="id_password1">Senha:</label> <input name="password1" maxlength="128" id="id_password1" type="password"></p>
		<p><label for="id_password2">Confirme a Senha:</label> <input name="password2" maxlength="128" id="id_password2" type="password"></p>
		<p><label for="id_primeiro_nome">Primeiro nome:</label> <input name="primeiro_nome" maxlength="20" id="id_primeiro_nome" type="text"></p>
		<p><label for="id_segundo_nome">Segundo nome:</label> <input name="segundo_nome" maxlength="60" id="id_segundo_nome" type="text"></p>
		<p><label for="id_cep">Cep:</label> <input name="cep" maxlength="9" id="id_cep" type="text"></p>
		<input type="submit" name="submit" value="Registrar" />
	</form>
</body>
</html>