Aluno/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Aluno'

urlpatterns = [
	path('Painel-Aluno', PainelAlunoView.as_view(), name='painelAlunoUrl'),
	path('Painel-Aluno/Perfil', PerfilView.as_view(), name='perfilUrl')
]

Corretor/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Corretor'

urlpatterns = [
	path('Painel-Corretor', PainelCorretorView.as_view(), name='painelCorretorUrl'),
]

Visitante/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'Visitante'

urlpatterns = [
	path('', IndexView.as_view(), name='indexUrl'),
	path('cadastro/aluno', StudentRegisterView.as_view(), name='studentRegisterUrl'),
	path('login', auth_views.login, {'template_name': 'Visitante/login.html'}, name='login'),
	path('logout', auth_views.logout, {'template_name': 'Visitante/index.html'}, name='logout'),
	path('UsoInvalido', InfoFalhaView.as_view(), name='infoFalhaUrl')
]

projeto_redacao/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('Visitante.urls')),
    url(r'^', include('Aluno.urls')),
    url(r'^', include('Redacao.urls')),
    url(r'^', include('Corretor.urls')),
    url(r'^', include('Pagamento.urls')),
    url(r'^retorno/pagseguro/', include('pagseguro.urls')),
]

Aluno/forms.py
from django import forms

from django.utils import timezone

from Usuarios.models import User

class ModifyUserForm(forms.Form):
	email             = forms.EmailField(max_length=255, required=False)
	password1         = forms.CharField(label='Senha', widget=forms.PasswordInput, required=False, max_length=128)
	password2         = forms.CharField(label='Confirme a Senha', widget=forms.PasswordInput, required=False, max_length=128)
	primeiro_nome     = forms.CharField(required=False, max_length=20)
	segundo_nome      = forms.CharField(required=False, max_length=60)
	cep               = forms.CharField(required=False, max_length=9)

	def save(self, user, commit=True):
		if self['email'].data:
			user.email = self['email'].data
		if self['password1'].data:
			user.set_password(self.cleaned_data["password1"])
		if self['primeiro_nome'].data:
			user.primeiro_nome = self['primeiro_nome'].data
		if self['segundo_nome'].data:
			user.segundo_nome = self['segundo_nome'].data
		if self['cep'].data:
			user.cep = self['cep'].data

		if commit:
			user.save()
		return user

class CompraForm(forms.Form):
	quantidade        = forms.IntegerField()

Visitante/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.models import Group

from Usuarios.models import User


class RegisterForm(forms.ModelForm):
	password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirme a Senha', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email',)

	def clean_email(self):
		email = self.cleaned_data.get('email')
		qs = User.objects.filter(email=email)
		if qs.exists():
			raise forms.ValidationError("email is taken")
		return email

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		if commit:
			user.save()
		return user

class StudentRegisterForm(RegisterForm):
	password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirme a Senha', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email', 'primeiro_nome', 'segundo_nome', 'cep')

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		user.save()
		a = Group.objects.get(name='Alunos') 
		user.groups.add(a)
		if commit:
			user.save()
		return user

class TeacherRegisterForm(RegisterForm):
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email',)

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2
		
	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		user.save(commit=False)
		p = Group.objects.get(name='Corretores') 
		user.groups.add(p)
		if commit:
			user.save()
		return user

Visitante/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import StudentRegisterForm, TeacherRegisterForm, RegisterForm

class IndexView(View):
	def get(self, request):
		perm_aluno = request.user.has_perm('Usuarios.acesso_painel_aluno')
		perm_corretor = request.user.has_perm('Usuarios.acesso_painel_corretor')

		dic = {'perm_aluno': perm_aluno, 'perm_corretor': perm_corretor}

		return render(request, 'Visitante/index.html', dic)

class StudentRegisterView(View):
	def get(self, request):
		f = StudentRegisterForm()
		dic = { 'f': f }

		return render(request, 'Visitante/register.html', dic)
	def post(self, request):
		f = StudentRegisterForm(request.POST)

		if f.is_valid():
			f.save()
			messages.success(request, 'Conta criada com sucesso!')
		else:
			messages.error(request, f.errors)
		return redirect('Visitante:studentRegisterUrl')

class InfoFalhaView(View):
	def get(self, request):
		return render(request, 'Visitante/info.html')

Visitante/templates/Visitante/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	{% load static %}
	<link type="text/css" rel="stylesheet" href="{% static 'commun/css/reset.css' %}"/>
	<link type="text/css" rel="stylesheet" href="{% static 'commun/css/style.css' %}"/>

	<link type="text/css" rel="stylesheet" href="{% static 'commun/materialize/css/materialize.min.css' %}"  media="screen,projection"/>
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>Projeto Redação</title>
</head>

<body>
	{% block nav %}
	{% endblock %}

	<div class="container">
		{% block content %}
		{% endblock %}
	</div>
	
	<footer class="page-footer">
		<div class="footer-copyright">
			<div class="container">
				© 2014 Copyright Text
				<a class="grey-text text-lighten-4 right" href="#!">More Links</a>
			</div>
		</div>
	</footer>

	<!--JavaScript at end of body for optimized loading-->
	<script type="text/javascript" src="{% static 'commun/materialize/js/materialize.min.js' %}"></script>
</body>
</html>

Visitante/templates/Visitante/index.html
{% extends 'Visitante/base.html' %}

{% block nav %}
<nav>
	<div class="nav-wrapper red lighten-5 text-darken-2">
		<div class="container">
			<ul class="left">
				<li><h5 href="#">REDação</h5></li>
			</ul>
			<ul class="right">
	        	<li><a class="waves-effect waves-light btn" href="{% url 'Visitante:login' %}">Entrar</a></li>
	    	</ul>
    	</div>
	</div>
</nav>
{% endblock %}

{% block content %}
	<center>
		<h1>Bem vindo ao Projeto Redação</h1>
		{% load static %}
		<p>Aqui será a nova casa para suas redações</p>
		{% if user.is_authenticated %}
			Oi {{ user.email }}!
			<a href="{% url 'Visitante:logout' %}?next=/"> Logout</a>
			<br>
			<br>
		{% else %}
			<h2><a href="{% url 'Visitante:studentRegisterUrl' %}">Cadastrar-se como Aluno!</a></h2>
		{% endif %}
		{% if perm_aluno %}
			<a href="{% url 'Aluno:painelAlunoUrl' %}"> Painel do Aluno </a>
			<br>
			<br>
		{% endif %}
		{% if perm_corretor %}
			<a href="{% url 'Corretor:painelCorretorUrl' %}"> Painel do Corretor </a>
		{% endif %}
		{% if not perm_corretor and not perm_aluno %}
			<a href="{% url 'Visitante:login' %}">login</a>
		{% endif %}
	</center>
{% endblock %}

Visitante/templates/Visitante/info.html
{% extends 'Visitante/base.html' %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

Visitante/templates/Visitante/login.html
{% extends 'Visitante/base.html' %}

{% block content %}

{% if messages %}
<ul>
	{% for message in messages %}
	<li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}

<h1>Login</h1>

<div class="card">
	<div class="card-content">
		<form method="POST">
			{% csrf_token %}

			<div class="row">
				<div class="input-field col s12">
					<i class="material-icons prefix">mail_outline</i>
					<input name="username" autofocus="" maxlength="254" required="" id="id_username" type="text" class="validate"/>
					<label class="active" for="id_username">Email</label>
				</div>
				<div class="input-field col s12">
					<i class="material-icons prefix">lock_outline</i>
					<input name="password" required="" id="id_password" type="password" class="validate"/>
					<label class="active" for="id_password">Senha</label>
				</div>
				<button class="btn waves-effect waves-light" type="submit" name="action">Entrar</button>
			</div>
		</form>
	</div>
</div>

{% endblock %}

Visitante/templates/Visitante/register.html
{% extends 'Visitante/base.html' %}

{% block content %}

{% if messages %}
<ul>
	{% for message in messages %}
	<li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}

<h1>Cadastro</h1>
<div class="card">
	<div class="card-content">
		<form method="POST">
			{% csrf_token %}

			<div class="row">
				<div class="input-field col s12 m3">
					<input name="primeiro_nome" maxlength="30" required="" id="id_primeiro_nome" type="text">
					<label class="active" for="id_primeiro_nome">Primeiro nome</label>
				</div>
				<div class="input-field col s12 m6">
					<input name="segundo_nome" maxlength="60" required="" id="id_segundo_nome" type="text">
					<label class="active" for="id_segundo_nome">Segundo nome</label>
				</div>
				<div class="input-field col s12 m3">
					<input name="cep" maxlength="9" required="" id="id_cep" type="text">
					<label class="active" for="id_cep">CEP</label>
				</div>
				<div class="input-field col s12">
					<input name="email" maxlength="255" required="" id="id_email" type="email">
					<label class="active" for="id_email">Email</label>
				</div>
				<div class="input-field col s12 m6">
					<input name="password1" required="" id="id_password1" type="password">
					<label class="active" for="id_password1">Senha</label>
				</div>
				<div class="input-field col s12 m6">
					<input name="password2" required="" id="id_password2" type="password">
					<label class="active" for="id_password2">Confirme a Senha</label>
				</div>
			</div>
			<button class="btn waves-effect waves-light" type="submit" name="action">
				Matricular
			</button>
		</form>
	</div>
</div>
{% endblock %}